[workspace]
members = [
  "fastfib/script",
  "fib/script",
  "lcs/script",
  "lcs2/script",
  "sum/script",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
incremental = false
codegen-units = 1
